name: edupro_flutter_web
description: "MAYELE + - Plateforme de gestion scolaire et universitaire multi-tenant"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.2.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  shared_preferences: ^2.2.2
  http: ^1.2.2
  google_fonts: ^6.1.0
  intl: ^0.20.2
  printing: ^5.10.4
  pdf: ^3.10.1
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  test: ^1.24.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/Roboto-Regular.ttf
    - assets/fonts/Roboto-Medium.ttf

flutter_launcher_icons:
  android: true
  ios: false
  image_path: assets/branding/mayele_icon.png
  adaptive_icon_background: "#071B29"
  adaptive_icon_foreground: assets/branding/mayele_icon.png
  web:
    generate: true
    image_path: assets/branding/mayele_icon.png
    background_color: "#071B29"
    theme_color: "#071B29"
  windows:
    generate: true
    image_path: assets/branding/mayele_icon.png
    icon_size: 256
  macos:
    generate: true
    image_path: assets/branding/mayele_icon.png
